### ISSUE TITLE
Roles collection is empty on first run

### ISSUE THREAD

**Issue by aksalj** [kevgathuku/docue#23]
Hey!

On first run, following the instructions in `README.md`, I can't move past sign up. It signs me up but with a `null` role; so every time I try to login I get:

![screen shot 2016-03-04 at 6 46 33 pm](https://cloud.githubusercontent.com/assets/2534772/13531810/7e2b6048-e239-11e5-8e84-4c99c36d09cb.png)

This is what I think is causing it:
- On sign up, no role info is sent along with other details. The default role is used instead; as seen [here](https://github.com/kevgathuku/docue/blob/master/server/controllers/users.js#L24)
- Then, roles are looked up before a user is created so they can have a valid role (see [here](https://github.com/kevgathuku/docue/blob/master/server/controllers/users.js#L41-L43) )
- **But if the `roles` collection is empty, the lookup will not return any `role` and user is saved with `null` as shown [here](https://github.com/kevgathuku/docue/blob/master/server/controllers/users.js#L48-L56)**

One solution could be to populate the `roles` collection on first run.

---

```
mac os 10.11.2
node v5.6.0
npm 3.6.0
chrome 48.0.2564.116
```

**Comment by kevgathuku** [comment]
Hey @aksalj,
Thanks for bringing this up. I should have dealt with this better.
You are correct, there are no roles by default, yet a role is required when trying to sign up a user.
What you've suggested about populating the roles is actually something I have thought about, but haven't got around to implementing yet.
A workaround you could use in the meantime is creating the roles manually in MongoDB. I know this is not ideal, but it's the only solution I have in mind right now.
If you've got any ideas on how this could be solved, I would be open to them.

**Comment by kevgathuku** [comment]
Fixed in https://github.com/kevgathuku/docue/commit/9f47ae03a6b00dac87ec39cd56b3434cbcbd3444
